config.gem 'cucumber', :lib => false, :version => '0.4.3'
config.gem 'webrat', :lib => false, :version => '0.5.3'
config.gem 'rspec', :lib => false, :version => '1.2.9'
config.gem 'rspec-rails', :lib => false, :version => '1.2.9'
config.gem 'email_spec', :lib => false, :version => '0.4.0'
config.gem 'machinist', :lib => false, :version => '1.0.6'
config.gem 'pickle', :lib => false, :version => '0.2.1'
config.gem 'faker', :lib => false, :version => '0.3.1'
config.gem 'mechanize'
