class AddIndexes < ActiveRecord::Migration[4.2]
  def self.up
    add_index 'memberships', 'site_id'
    add_index 'memberships', 'user_id'
    add_index 'content_translations', 'content_id'
    add_index 'teams', 'site_id'
    add_index 'teams', 'race_id'
    add_index 'comments', 'site_id'
    add_index 'comments', 'section_id'
    add_index 'comments', 'commentable_id'
    add_index 'comments', 'author_id'
    add_index 'comments', 'board_id'
    add_index 'riders', 'team_id'
    add_index 'counters', 'owner_id'
    add_index 'sections', 'site_id'
    add_index 'sections', 'parent_id'
    add_index 'points', 'team_id'
    add_index 'activities', 'site_id'
    add_index 'activities', 'section_id'
    add_index 'activities', 'author_id'
    add_index 'activities', 'object_id'
    add_index 'cached_pages', 'site_id'
    add_index 'cached_pages', 'section_id'
    add_index 'cached_page_references', 'cached_page_id'
    add_index 'cached_page_references', 'object_id'
    add_index 'contents', 'site_id'
    add_index 'contents', 'section_id'
    add_index 'contents', 'author_id'
    add_index 'contents', 'parent_id'
    add_index 'categories', 'section_id'
    add_index 'categories', 'parent_id'
    add_index 'roles', 'user_id'
    add_index 'roles', 'context_id'
    add_index 'roles', 'ancestor_context_id'
    add_index 'plugin_configs', 'owner_id'
    add_index 'categorizations', 'categorizable_id'
    add_index 'categorizations', 'category_id'
  end

  def self.down
    remove_index 'memberships', 'site_id'
    remove_index 'memberships', 'user_id'
    remove_index 'content_translations', 'content_id'
    remove_index 'teams', 'site_id'
    remove_index 'teams', 'race_id'
    remove_index 'comments', 'site_id'
    remove_index 'comments', 'section_id'
    remove_index 'comments', 'commentable_id'
    remove_index 'comments', 'author_id'
    remove_index 'comments', 'board_id'
    remove_index 'riders', 'team_id'
    remove_index 'counters', 'owner_id'
    remove_index 'sections', 'site_id'
    remove_index 'sections', 'parent_id'
    remove_index 'points', 'team_id'
    remove_index 'activities', 'site_id'
    remove_index 'activities', 'section_id'
    remove_index 'activities', 'author_id'
    remove_index 'activities', 'object_id'
    remove_index 'cached_pages', 'site_id'
    remove_index 'cached_pages', 'section_id'
    remove_index 'cached_page_references', 'cached_page_id'
    remove_index 'cached_page_references', 'object_id'
    remove_index 'contents', 'site_id'
    remove_index 'contents', 'section_id'
    remove_index 'contents', 'author_id'
    remove_index 'contents', 'parent_id'
    remove_index 'categories', 'section_id'
    remove_index 'categories', 'parent_id'
    remove_index 'roles', 'user_id'
    remove_index 'roles', 'context_id'
    remove_index 'roles', 'ancestor_context_id'
    remove_index 'plugin_configs', 'owner_id'
    remove_index 'categorizations', 'categorizable_id'
    remove_index 'categorizations', 'category_id'
  end
end
